# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baaf7a49fd4e1e2ceed9891f5ff10ef521ca71082b87eb5804c2cde6483bb6148c8c3679fe040fbe85e139d148bf6d975c9bbdf0607d4334a767b64fc60c80c7

test:
  secret_key_base: 97fb93074106391dc8d704e75502cd2e4560f58f649e837b267f78e94042afd5b95e5e68c2de4f33567bae649fa6d4974bc718f6c429d37d21aca9f334a6e4f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
